django_yemmyharryscrumy/yemmyharryscrumy/urls.py
from django.urls import path, include
from . import views

app_name = 'yemmyharryscrumy'

urlpatterns = [
    path('', views.index, name="index"),
    path('movegoal/<int:goal_id>/', views.move_goal, name='move_goal'),
    path('addgoal/', views.add_goal, name="add_goal"),
    path('home/', views.home, name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include
from django_yemmyharryscrumy.yemmyharryscrumy import views
from websocket import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('yemmyharryscrumy/', include('django_yemmyharryscrumy.yemmyharryscrumy.urls')),
    path('websocket/', include('websocket.urls')),
]

django_yemmyharryscrumy/yemmyharryscrumy/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.

class GoalStatus(models.Model):
    status_name     =       models.CharField(max_length=200)

    def __str__(self):
        return self.status_name

class ScrumyGoals(models.Model):
    goal_name   =   models.CharField(max_length=200)
    goal_id     =   models.IntegerField(default=0)
    created_by  =   models.CharField(max_length=200)
    moved_by    =   models.CharField(max_length=200)
    owner       =   models.CharField(max_length=200)
    goal_status =   models.ForeignKey(GoalStatus, on_delete=models.PROTECT, related_name='number_of_goals')
    user        =   models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_name')


    class Meta:
        ordering  =  ['-id']

    def __str__(self):
        return self.goal_name



class ScrumyHistory(models.Model):
    moved_by         =   models.CharField(max_length=200)
    created_by       =   models.CharField(max_length=200)
    moved_from       =   models.CharField(max_length=200)
    moved_to         =   models.CharField(max_length=200)
    time_of_action   =   models.DateTimeField(auto_now_add=True)
    goal             =   models.ForeignKey(ScrumyGoals, on_delete=models.CASCADE, related_name='score')


    def __str__(self):
        return self.created_by

django_yemmyharryscrumy/yemmyharryscrumy/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ScrumyGoals

class SignupForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password']



class CreateGoalForm(forms.ModelForm):
    
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name' , 'user']

django_yemmyharryscrumy/yemmyharryscrumy/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import models
from . import models
from .models import ScrumyHistory, GoalStatus, ScrumyGoals, User
from django.contrib.auth.models import Group
import random
from django.contrib.auth import login
from django.contrib.auth import authenticate
from . import forms
developer_group = Group.objects.get(name = 'Developer')
group_owner = Group.objects.get(name = 'Owner')
group_qa = Group.objects.get(name = 'Quality Assurance')
group_admin = Group.objects.get(name = 'Admin')



# def index(request):
#     return HttpResponse(ScrumyGoals.objects.filter(goal_name="Learn Django"))


# this index enables successful signup
def index(request): 
    if request.method == 'POST': 
         form = forms.SignupForm(request.POST) 
         if form.is_valid():
            new_user = form.save(commit = False)
            # new_user.set_password(request.POST.get('password'))
            new_user.set_password(new_user.password)
            new_user.save()
            developer_group.user_set.add(new_user)
            return HttpResponse('Your account has been created successfully')   
    else: 
         form = forms.SignupForm()
         context = {
             'form': form,
         }
         return render(request, 'yemmyharryscrumy/index.html', context)




# def move_goal(request,goal_id):
#     try: 
#          goal = ScrumyGoals.objects.get(goal_id=goal_id)
#     except Exception as e:
#         context = {'error': 'A record with that goal id does not exist',}
#         return render(request, 'yemmyharryscrumy/exception.html', context)
#     else: return HttpResponse(goal.goal_name)
#     return HttpResponse(goal.goal_name)


# this enables movement of users in different groups and set boundaries to what is allowable
   
def move_goal(request, goal_id):
    if request.method == 'POST':
        goal = ScrumyGoals.objects.get(goal_id = goal_id)
        verify_goal = GoalStatus.objects.get(status_name = "Verify Goal")
        done_goal = GoalStatus.objects.get(status_name = "Done Goal")
        if request.user.groups.filter(name__in=[developer_group]).exists() and goal.created_by != request.user.username or request.user.groups.filter(name__in=[group_owner]).exists() and goal.created_by != request.user.username:
            return render(request, 'yemmyharryscrumy/exception.html', {'error': 'Permission denied'})
        elif request.user.groups.filter(name__in=[developer_group]).exists() and goal.goal_status == done_goal:
            return render(request, 'yemmyharryscrumy/exception.html', {'error': 'Permission denied'})
        elif request.user.groups.filter(name__in=[developer_group]).exists() and request.POST.get('group1') == 'Done Goal':
            return render(request, 'yemmyharryscrumy/exception.html', {'error': 'Permission denied'})
        elif request.user.groups.filter(name__in=[group_qa]).exists() and goal.goal_status != verify_goal and goal.created_by != request.user.username and (request.POST.get('group1') in ['Done Goal', 'Daily Goal', 'Weekly Goal', 'Verify Goal']):
            return render(request, 'yemmyharryscrumy/exception.html', {'error': 'Permission denied'})
        elif request.user.groups.filter(name__in=[group_qa]).exists() and goal.goal_status == verify_goal and goal.created_by != request.user.username and (request.POST.get('group1') in ['Daily Goal', 'Weekly Goal', 'Verify Goal']):
            return render(request, 'yemmyharryscrumy/exception.html', {'error': 'Permission denied'})
        else:  
            goal.goal_status = GoalStatus.objects.get(status_name = request.POST.get('group1'))
            goal.save()
            return redirect("yemmyharryscrumy:home")                      
    else:
        return render(request, 'yemmyharryscrumy/movegoal.html')


def add_goal(request):
    if request.method == 'POST':
        form = forms.CreateGoalForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user']
            new_user = form.save(commit= False)




        list = [] #created an empty list/array

        goal_list = ScrumyGoals.objects.all() 

        for i in goal_list:     #go through all instances of scrumygoals
            list.append(int(i.goal_id))     #add the number in list to the goalid of scrumygoals

        while True:
            number = random.randint(1000, 9999)  #generates a random number

            if number in list:
                continue
            else:
            
             
                new_user.goal_id=number
                new_user.created_by=user
                new_user.moved_by=user
                new_user.owner=user
                new_user.goal_status= GoalStatus.objects.get(status_name="Weekly Goal")
                new_user.save()
              
                return redirect("yemmyharryscrumy:home")

    else:
        form = forms.CreateGoalForm()
        context = {
            'form': form,
        }
    return render( request, 'yemmyharryscrumy/addgoal.html', context)
    
def home(request):
    context = { 'users': User.objects.all(),
                 'weekly_goals': ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name="Weekly Goal")),
                 'daily_goals': ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name="Daily Goal")),
                 'verify_goals': ScrumyGoals.objects.filter(goal_status=GoalStatus.objects.get(status_name="Verify Goal")),
                 'done_goals': ScrumyGoals.objects.filter(goal_status= GoalStatus.objects.get(status_name="Done Goal")),
                    }
    return render(request, 'yemmyharryscrumy/home.html', context)
    

django_yemmyharryscrumy/yemmyharryscrumy/templates/yemmyharryscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Add goal</title>
</head>
<body class="container">


    {% if user.is_authenticated %}
        <div class="center"><h6 style="font-size: smaller;">Logged in as</h6> <div class="chip"> 
        {{user.username}} <i class="close material-icons">person</i>
        </div><br><br></div>
    {% endif %}
    

    {% if form %}
    <form method="POST">
        {% csrf_token %}
        
            {{ form.label }}
            {{ form }}

        

      <!-- <div class="input-field col s12">
        <input type="text" name="goal_name" class="validate">
        <label for="goal">Goal</label>
      </div>
      <div class="input-field col s12">
        <label for="">Created for:</label><br><br>
        <select name="user" id="">
            {% for user in users %}
                <option value="">
                    {{user.username}}
                </option>
            {% endfor %}
        </select>
      
           
        
      </div><br> -->
      <div>
          <input type="submit" value="Submit" class="waves-effect waves-teal btn"></input>
      </div>
    </form><br>

    <a href="{% url 'yemmyharryscrumy:home' %}"> Home </a> 
    {% endif %}

</body>
</html>

django_yemmyharryscrumy/yemmyharryscrumy/templates/yemmyharryscrumy/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Exception</title>
</head>
<body>
    <p>{{error}}</p>
</body>
</html>

django_yemmyharryscrumy/yemmyharryscrumy/templates/yemmyharryscrumy/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <title>yemmyharryscrumy</title>
    <style>
        table,th,td {
            border: 1px solid grey;
            padding: 10px;
            border-collapse: collapse;
        }
    </style>
    
</head>
<body>
    
    <table>
        <nav>
          <div class="nav-wrapper">
            <a href="#" class="brand-logo left">My Scrumy Goals</a>
          </div>
        </nav> <br>
        {% if user.is_authenticated %}
                <div class="center"><h6 style="font-size: smaller;">Logged in as</h6> <div class="chip"> 
            {{user.username}} <i class="close material-icons">person</i>
                </div><br><br></div>
        {% endif %}

        <tr>
            <th>User</th>
            <th>Weekly Goals</th>
            <th>Daily Goals</th>
            <th>Verify Goals</th>
            <th>Done Goals</th>
        </tr>
        <!-- using scrumygoals.objects.all in context -->
    <!-- {% for goal in scrumygoals %}
        <tr>
            <td>{{goal.user}}</td>
            <td>
                {% if goal.goal_status.status_name == "Weekly Goal" %}
                    <div>{{goal.goal_name}}:{{goal.goal_id}}</div>
                {% endif %}
            </td>
            <td>
                {% if goal.goal_status.status_name == "Daily Goal" %}
                    <div>{{goal.goal_name}}:{{goal.goal_id}}</div>
                {% endif %}
            </td>
            <td>
                {% if goal.goal_status.status_name == "Verify Goal" %}
                    <div>{{goal.goal_name}}:{{goal.goal_id}}</div>
                {% endif %}
            </td>
            <td>
                {% if goal.goal_status.status_name == "Done Goal" %}
                    <div>{{goal.goal_name}}:{{goal.goal_id}}</div>
                {% endif %}
            </td>

        </tr>
    {% endfor %} -->
    {% for user in users %}
        <tr>
            <td>{{user.username}}</td>
            <td>
                {% for weekly in user.user_name.all %}
                {% if weekly in weekly_goals %}
                    <div>
                        {{weekly.goal_name}}:{{weekly.goal_id}}
                        <p><a href="{% url 'yemmyharryscrumy:move_goal' weekly.goal_id %}">Move goal</a></p>

                    </div>
                {% endif %}
                {% endfor%}
            </td>
            <td>
                {% for daily in user.user_name.all %}
                {% if daily in daily_goals %}
                    <div>
                        {{daily.goal_name}}:{{daily.goal_id}}
                        <p><a href="{% url 'yemmyharryscrumy:move_goal' daily.goal_id %}">Move goal</a></p>
                    </div>
                {% endif %}
                {% endfor%}
            </td>
            <td>
                {% for verify in user.user_name.all %}
                {% if verify in verify_goals %}
                    <div>
                        {{verify.goal_name}}:{{verify.goal_id}}
                        <p><a href="{% url 'yemmyharryscrumy:move_goal' verify.goal_id %}">Move goal</a></p>
                    </div>
                {% endif %}
                {% endfor%}
            </td>
            <td>
                {% for done in user.user_name.all %}
                {% if done in done_goals %}
                    <div>
                        {{done.goal_name}}:{{done.goal_id}}
                        <p><a href="{% url 'yemmyharryscrumy:move_goal' done.goal_id %}">Move goal</a></p>
                    </div>
                {% endif %}
                {% endfor%}
            </td>

        </tr>
    {% endfor %}
    </table>
    <p><a href="{% url 'yemmyharryscrumy:add_goal'%}">Add goal</a></p>
</body>
</html>

django_yemmyharryscrumy/yemmyharryscrumy/templates/yemmyharryscrumy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title> User Creation Page </title>
</head>
<body class="container">    

    <h3>Sign Up</h3>

        <form method="POST">
        {% csrf_token %}
            {% for input in form %}
                    
                <div class="input-field">
                    
                    {{ form.errors}}
                    {{ input.label }}
                    {{ input }}
                    
    
                    
                </div>
                <!-- <div class="input-field col s12 l6">
                    <input type="text" id="last_name" class="validate">
                    <label for="last_name">Last Name</label>
                </div>
                <div class="input-field col s12">
                    <input type="email" id="email" class="validate">
                    <label for="email" data-error="wrong" data-success="right">Email</label>
                </div>
                <div class="input-field col s12">
                    <textarea id="textarea1" class="materialize-textarea"></textarea>
                    <label for="textarea1">Textarea</label>
                </div> -->
            {% endfor %}
            <button type="submit" class="waves-effect waves-light btn">Sign up</button>
        </form><br>
        <!-- <a href="{% url 'yemmyharryscrumy:add_goal' %}"> add goal </a> -->
        
        
</body>
</html>

django_yemmyharryscrumy/yemmyharryscrumy/templates/yemmyharryscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Move Goal</title>
</head>
<body>
  <form method="POST">
        {% csrf_token %}

                <h5>Goal Selection</h5>
                <p>
                <label>
                    <input name="group1" type="radio" checked value="Daily Goal"/>
                    <span>Daily Goal</span>
                </label>
                </p>
                <p>
                <label>
                    <input name="group1" type="radio" value="Weekly Goal"/>
                    <span>Weekly Goal</span>
                </label>
                </p>
                <p>
                <label>
                    <input  name="group1" type="radio"  value="Verify Goal"/>
                    <span>Verify Goal</span>
                </label>
                </p>
                <p>
                <label>
                    <input name="group1" type="radio" value="Done Goal"/>
                    <span>Done Goal</span>
                </label>
                </p>
                <div>
                    <input type="submit" value="Move Goal" class="waves-effect waves-teal btn"></input>
                </div>
                

  </form>
        
</body>
</html>